services:
  postgres:
    image: postgres:16-alpine
    container_name: minurl-postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: minurl
      POSTGRES_USER: minurl
      POSTGRES_PASSWORD: minurl
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local
